services:
  - type: web
    name: multilingual-news-platform
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache/huggingface
      - key: HF_HOME
        value: /opt/render/project/.cache/huggingface
      - key: HF_DATASETS_CACHE
        value: /opt/render/project/.cache/huggingface
